name = "leanin"
version = "0.1.0"
defaultTargets = ["LeanIn", "spike", "wakerspike", "controls", "dynamics", "bridgecontrols"]

[[lean_lib]]
name = "LeanIn"

[[lean_exe]]
name = "spike"
root = "Spike"

[[lean_exe]]
name = "wakerspike"
root = "WakerSpike"

[[lean_exe]]
name = "controls"
root = "Controls"

[[lean_exe]]
name = "dynamics"
root = "Dynamics"

[[lean_exe]]
name = "bridgecontrols"
root = "BridgeControls"
